### ISSUE TITLE
Missing html file and css not responding

### ISSUE THREAD

**Issue by riannazandbelt** [riannazandbelt/svg-smiley-face#1]
Hi @hellachella and @jessjodoin,

I'm having an issue when trying to submit my assignment through Markbot. It states that my index.html file is missing or misspelled but I can't understand why because I've spelled it correctly and I've placed it in the right folder (smiley-face).

Also, my css is not responding with the changes I've made within the main.css file. I believe it's linked correctly but it remains unresponsive. In the written lesson the css file is within the smiley-face folder, and when I did that the smiley face was responsive but Markbot said that the file was missing or misspelled. So I moved the css folder to stand alone and the message about the missing/misspelling went away but that's when the css was unresponsive. So I'm not sure where to go with this, any advice would be greatly appreciated :) 

Thanks!

**Comment by JessJodoin** [comment]
The index isn't showing up because you have it placed inside a folder called smiley-face so if you move it out of that folder your index should be recognized by markbot and your css should work

**Comment by riannazandbelt** [comment]
Ok thanks, I'll try that out
